Exposed getDialect
hyperjump-io/json-schema pull request #66
Opened 2024-06-08 07:36 UTC by diyaayay

2024-06-08 18:21 UTC, jdesrosiers requested changes
Looks good. Could you also add an entry for this function in the README under the Experimental API.

2024-06-08 18:21 UTC, jdesrosiers commented on lib/experimental.d.ts
> +export const getDialect: (dialectId: string) => { [keyword: string]: string };
Let's use `Record` here instead.

```suggestion
export const getDialect: (dialectId: string) => Record<string, string>;
```

2024-06-08 19:32 UTC, diyaayay commented on lib/experimental.d.ts
> +export const getDialect: (dialectId: string) => { [keyword: string]: string };
Done.

2024-06-09 01:14 UTC, jdesrosiers approved these changes

2024-06-09 01:17 UTC, merged